# Generated by Django 4.0.5 on 2022-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
