# Generated by Django 4.0.5 on 2022-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_alter_measure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
