# Generated by Django 4.0.5 on 2022-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0003_alter_measure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
